# Generated by Django 4.2.3 on 2023-09-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Distric',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_available',
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='YourDefaultLocation', max_length=100),
        ),
    ]
